cd ~/Documents/gps-on-aerosol/

load aeronet_svm_6
load aeronet_gp_6

close all


params.width = 9;
params.height = 8;
params.dot_size = 6;
params.name = '';
params.x_label = 'AERONET AOD';
params.y_label = 'MODIS Terra';

% Draw a scatter plot 
figure;%('Position',[left, bottom, width, height])

max_t = max(t_terra);
params.bounds = [0, max_t, 0 , max_t];
params.step = 0.03*max_t/4;

% GP Aeronet - corrected MODIS Terra comparison
%plot(t_terra,t_mean_terra,'+r')   
[onetooneh,meanh,SDh] = ...
    correlation_plot(t_mean_terra, t_sd_terra, t_terra, params);

raw = plot(t_terra,p_terra(:,end),'+','Color',[0.2 0.2 0.2],...
    'MarkerSize',4);   

svm = plot(t_terra,SVM_terra,'o','Color',[0.2 0.2 0.2],...
    'MarkerSize',3); 

meanh = plot(t_terra,t_mean_terra,'.');
set(meanh, ... 
  'LineStyle', 'none', ...
  'LineWidth', 0.75, ...
  'Marker', '.', ...
  'MarkerSize', params.dot_size, ...
  'Color', [0 0 0.8] ...
  );

% Raw Aeronet - MODIS Terra comparison

l =legend( ...
[onetooneh,raw,svm,meanh,SDh], ...
'1:1', ...
['raw, $R=' num2str(rr_terra,2),'$'],...
['\svm, $R=' num2str(rr_svm_terra,2),'$'],...
    ['\gp\ mean, $R=' num2str(rr_gp_terra,2),'$'] , ...
    ['\gp\ $\pm 2$\,\SD'],...
'Location','NorthWest');

legend boxoff

matlabfrag('Terra')

% Draw a scatter plot 
figure;%('Position',[left, bottom, width, height])

max_t = max(t_aqua);
params.bounds = [0, max_t, 0 , max_t];
params.step = 0.03*max_t/4;

params.y_label = 'MODIS Aqua';
% GP Aeronet - corrected MODIS Terra comparison
%plot(t_aqua,t_mean_aqua,'+r')   1
[onetooneh,meanh,SDh] = ...
    correlation_plot(t_mean_aqua, t_sd_aqua, t_aqua, params);

raw = plot(t_aqua,p_aqua(:,end),'+','Color',[0.2 0.2 0.2],...
    'MarkerSize',4);    

svm = plot(t_aqua,SVM_aqua,'o','Color',[0.2 0.2 0.2],...
    'MarkerSize',3); 

meanh = plot(t_aqua,t_mean_aqua,'.');
set(meanh, ... 
  'LineStyle', 'none', ...
  'LineWidth', 0.75, ...
  'Marker', '.', ...
  'MarkerSize', params.dot_size, ...
  'Color', [0 0 0.8] ...
  );

% Raw Aeronet - MODIS Terra comparison

l =legend( ...
[onetooneh,raw,svm,meanh,SDh], ...
'1:1', ...
['raw, $R=' num2str(rr_aqua,2),'$'],...
['\svm, $R=' num2str(rr_svm_aqua,2),'$'],...
    ['\gp\ mean, $R=' num2str(rr_gp_aqua,2),'$'] , ...
    ['\gp\ $\pm 2$\,\SD'],...
'Location','NorthWest');

legend boxoff

matlabfrag('Aqua')
